// Code generated by "stringer -type=DataConstraintKind -output=data-constraint-kind_string.go"; DO NOT EDIT.

package appdef

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataConstraintKind_null-0]
	_ = x[DataConstraintKind_MinLen-1]
	_ = x[DataConstraintKind_MaxLen-2]
	_ = x[DataConstraintKind_Pattern-3]
	_ = x[DataConstraintKind_Count-4]
}

const _DataConstraintKind_name = "DataConstraintKind_nullDataConstraintKind_MinLenDataConstraintKind_MaxLenDataConstraintKind_PatternDataConstraintKind_Count"

var _DataConstraintKind_index = [...]uint8{0, 23, 48, 73, 99, 123}

func (i DataConstraintKind) String() string {
	if i >= DataConstraintKind(len(_DataConstraintKind_index)-1) {
		return "DataConstraintKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataConstraintKind_name[_DataConstraintKind_index[i]:_DataConstraintKind_index[i+1]]
}
