// Code generated by "stringer -type=DefKind -output=def-kind_string.go"; DO NOT EDIT.

package appdef

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DefKind_null-0]
	_ = x[DefKind_GDoc-1]
	_ = x[DefKind_CDoc-2]
	_ = x[DefKind_ODoc-3]
	_ = x[DefKind_WDoc-4]
	_ = x[DefKind_GRecord-5]
	_ = x[DefKind_CRecord-6]
	_ = x[DefKind_ORecord-7]
	_ = x[DefKind_WRecord-8]
	_ = x[DefKind_ViewRecord-9]
	_ = x[DefKind_ViewRecord_PartitionKey-10]
	_ = x[DefKind_ViewRecord_ClusteringColumns-11]
	_ = x[DefKind_ViewRecord_Key-12]
	_ = x[DefKind_ViewRecord_Value-13]
	_ = x[DefKind_Object-14]
	_ = x[DefKind_Element-15]
	_ = x[DefKind_QueryFunction-16]
	_ = x[DefKind_Command-17]
	_ = x[DefKind_FakeLast-18]
}

const _DefKind_name = "DefKind_nullDefKind_GDocDefKind_CDocDefKind_ODocDefKind_WDocDefKind_GRecordDefKind_CRecordDefKind_ORecordDefKind_WRecordDefKind_ViewRecordDefKind_ViewRecord_PartitionKeyDefKind_ViewRecord_ClusteringColumnsDefKind_ViewRecord_KeyDefKind_ViewRecord_ValueDefKind_ObjectDefKind_ElementDefKind_QueryFunctionDefKind_CommandDefKind_FakeLast"

var _DefKind_index = [...]uint16{0, 12, 24, 36, 48, 60, 75, 90, 105, 120, 138, 169, 205, 227, 251, 265, 280, 301, 316, 332}

func (i DefKind) String() string {
	if i >= DefKind(len(_DefKind_index)-1) {
		return "DefKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DefKind_name[_DefKind_index[i]:_DefKind_index[i+1]]
}
