// Code generated by "stringer -type=LimitFilterOption -output=stringer_limitfilteroption.go"; DO NOT EDIT.

package appdef

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LimitFilterOption_ALL-0]
	_ = x[LimitFilterOption_EACH-1]
	_ = x[LimitFilterOption_count-2]
}

const _LimitFilterOption_name = "LimitFilterOption_ALLLimitFilterOption_EACHLimitFilterOption_count"

var _LimitFilterOption_index = [...]uint8{0, 21, 43, 66}

func (i LimitFilterOption) String() string {
	if i >= LimitFilterOption(len(_LimitFilterOption_index)-1) {
		return "LimitFilterOption(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LimitFilterOption_name[_LimitFilterOption_index[i]:_LimitFilterOption_index[i+1]]
}
