// Code generated by "stringer -type=TypeKind -output=stringer_typekind.go"; DO NOT EDIT.

package appdef

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeKind_null-0]
	_ = x[TypeKind_Any-1]
	_ = x[TypeKind_Tag-2]
	_ = x[TypeKind_Data-3]
	_ = x[TypeKind_GDoc-4]
	_ = x[TypeKind_CDoc-5]
	_ = x[TypeKind_ODoc-6]
	_ = x[TypeKind_WDoc-7]
	_ = x[TypeKind_GRecord-8]
	_ = x[TypeKind_CRecord-9]
	_ = x[TypeKind_ORecord-10]
	_ = x[TypeKind_WRecord-11]
	_ = x[TypeKind_ViewRecord-12]
	_ = x[TypeKind_Object-13]
	_ = x[TypeKind_Query-14]
	_ = x[TypeKind_Command-15]
	_ = x[TypeKind_Projector-16]
	_ = x[TypeKind_Job-17]
	_ = x[TypeKind_Workspace-18]
	_ = x[TypeKind_Role-19]
	_ = x[TypeKind_Rate-20]
	_ = x[TypeKind_Limit-21]
	_ = x[TypeKind_count-22]
}

const _TypeKind_name = "TypeKind_nullTypeKind_AnyTypeKind_TagTypeKind_DataTypeKind_GDocTypeKind_CDocTypeKind_ODocTypeKind_WDocTypeKind_GRecordTypeKind_CRecordTypeKind_ORecordTypeKind_WRecordTypeKind_ViewRecordTypeKind_ObjectTypeKind_QueryTypeKind_CommandTypeKind_ProjectorTypeKind_JobTypeKind_WorkspaceTypeKind_RoleTypeKind_RateTypeKind_LimitTypeKind_count"

var _TypeKind_index = [...]uint16{0, 13, 25, 37, 50, 63, 76, 89, 102, 118, 134, 150, 166, 185, 200, 214, 230, 248, 260, 278, 291, 304, 318, 332}

func (i TypeKind) String() string {
	if i >= TypeKind(len(_TypeKind_index)-1) {
		return "TypeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeKind_name[_TypeKind_index[i]:_TypeKind_index[i+1]]
}
