// Code generated by "stringer -type=LimitKind -output=stringer_limitkind.go"; DO NOT EDIT.

package appdef

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LimitKind_ALL-0]
	_ = x[LimitKind_EACH-1]
}

const _LimitKind_name = "LimitKind_ALLLimitKind_EACH"

var _LimitKind_index = [...]uint8{0, 13, 27}

func (i LimitKind) String() string {
	if i >= LimitKind(len(_LimitKind_index)-1) {
		return "LimitKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LimitKind_name[_LimitKind_index[i]:_LimitKind_index[i+1]]
}
