// Code generated by "stringer -type=LimitOption -output=stringer_limitoption.go"; DO NOT EDIT.

package appdef

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LimitOption_ALL-0]
	_ = x[LimitOption_EACH-1]
	_ = x[LimitOption_count-2]
}

const _LimitOption_name = "LimitOption_ALLLimitOption_EACHLimitOption_count"

var _LimitOption_index = [...]uint8{0, 15, 31, 48}

func (i LimitOption) String() string {
	if i >= LimitOption(len(_LimitOption_index)-1) {
		return "LimitOption(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LimitOption_name[_LimitOption_index[i]:_LimitOption_index[i+1]]
}
