// Code generated by "stringer -type=RateScope -output=stringer_ratescope.go"; DO NOT EDIT.

package appdef

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RateScope_null-0]
	_ = x[RateScope_AppPartition-1]
	_ = x[RateScope_Workspace-2]
	_ = x[RateScope_User-3]
	_ = x[RateScope_IP-4]
	_ = x[RateScope_count-5]
}

const _RateScope_name = "RateScope_nullRateScope_AppPartitionRateScope_WorkspaceRateScope_UserRateScope_IPRateScope_count"

var _RateScope_index = [...]uint8{0, 14, 36, 55, 69, 81, 96}

func (i RateScope) String() string {
	if i >= RateScope(len(_RateScope_index)-1) {
		return "RateScope(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RateScope_name[_RateScope_index[i]:_RateScope_index[i+1]]
}
