// Code generated by "stringer -type=VerificationKind -output=stringer_verificationkind.go"; DO NOT EDIT.

package appdef

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VerificationKind_EMail-0]
	_ = x[VerificationKind_Phone-1]
	_ = x[VerificationKind_FakeLast-2]
}

const _VerificationKind_name = "VerificationKind_EMailVerificationKind_PhoneVerificationKind_FakeLast"

var _VerificationKind_index = [...]uint8{0, 22, 44, 69}

func (i VerificationKind) String() string {
	if i >= VerificationKind(len(_VerificationKind_index)-1) {
		return "VerificationKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VerificationKind_name[_VerificationKind_index[i]:_VerificationKind_index[i+1]]
}
