// Code generated by "stringer -type=PrivilegeKind -output=stringer_privilegekind.go"; DO NOT EDIT.

package appdef

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PrivilegeKind_null-0]
	_ = x[PrivilegeKind_Insert-1]
	_ = x[PrivilegeKind_Update-2]
	_ = x[PrivilegeKind_Select-3]
	_ = x[PrivilegeKind_Execute-4]
	_ = x[PrivilegeKind_Inherits-5]
	_ = x[PrivilegeKind_count-6]
}

const _PrivilegeKind_name = "PrivilegeKind_nullPrivilegeKind_InsertPrivilegeKind_UpdatePrivilegeKind_SelectPrivilegeKind_ExecutePrivilegeKind_InheritsPrivilegeKind_count"

var _PrivilegeKind_index = [...]uint8{0, 18, 38, 58, 78, 99, 121, 140}

func (i PrivilegeKind) String() string {
	if i >= PrivilegeKind(len(_PrivilegeKind_index)-1) {
		return "PrivilegeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrivilegeKind_name[_PrivilegeKind_index[i]:_PrivilegeKind_index[i+1]]
}
