// Code generated by "stringer -type=OperationKind -output=stringer_operationkind.go"; DO NOT EDIT.

package appdef

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OperationKind_null-0]
	_ = x[OperationKind_Insert-1]
	_ = x[OperationKind_Update-2]
	_ = x[OperationKind_Activate-3]
	_ = x[OperationKind_Deactivate-4]
	_ = x[OperationKind_Select-5]
	_ = x[OperationKind_Execute-6]
	_ = x[OperationKind_ExecuteWithParam-7]
	_ = x[OperationKind_Inherits-8]
	_ = x[OperationKind_count-9]
}

const _OperationKind_name = "OperationKind_nullOperationKind_InsertOperationKind_UpdateOperationKind_ActivateOperationKind_DeactivateOperationKind_SelectOperationKind_ExecuteOperationKind_ExecuteWithParamOperationKind_InheritsOperationKind_count"

var _OperationKind_index = [...]uint8{0, 18, 38, 58, 80, 104, 124, 145, 175, 197, 216}

func (i OperationKind) String() string {
	if i >= OperationKind(len(_OperationKind_index)-1) {
		return "OperationKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperationKind_name[_OperationKind_index[i]:_OperationKind_index[i+1]]
}
