// Code generated by "stringer -type=GrantKind -output=stringer_grantkind.go"; DO NOT EDIT.

package appdef

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GrantKind_null-0]
	_ = x[GrantKind_Insert-1]
	_ = x[GrantKind_Update-2]
	_ = x[GrantKind_Select-3]
	_ = x[GrantKind_Execute-4]
	_ = x[GrantKind_Role-5]
}

const _GrantKind_name = "GrantKind_nullGrantKind_InsertGrantKind_UpdateGrantKind_SelectGrantKind_ExecuteGrantKind_Role"

var _GrantKind_index = [...]uint8{0, 14, 30, 46, 62, 79, 93}

func (i GrantKind) String() string {
	if i < 0 || i >= GrantKind(len(_GrantKind_index)-1) {
		return "GrantKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GrantKind_name[_GrantKind_index[i]:_GrantKind_index[i+1]]
}
