# options for analysis running
# https://golangci-lint.run/usage/linters/

linters:
  disable-all: true
  enable:
    - megacheck
    - govet
    - revive
    - gosec
    - stylecheck
    - misspell
    - errcheck
    - bidichk

# First stage linters
    - asciicheck      # Checks that all code identifiers does not have non-ASCII symbols in the name
    - durationcheck   # Check for two durations multiplied together
    - gochecknoinits  # Checks that no init functions are present in Go code.
    - gomnd

# Second stage linters
    - unconvert    # Remove unnecessary type conversions.
    - predeclared  # Find code that shadows one of Go's predeclared identifiers.
    - mirror       # Reports wrong mirror patterns of bytes/strings usage.
#    - nilerr       # Finds the code that returns nil even if it checks that the error is not nil.
    - testifylint  # Checks usage of github.com/stretchr/testify.


# Third stage linters
#------------------------------------
    - prealloc
    - perfsprint
    - nilnil
    - gocritic
    - exportloopref
    - errorlint
    - goconst
#------------------------------------

# For the future:
#------------------------------------
#    - testpackage
#    - nonamedreturns
#    - noctx
#?    - nestif
#    - musttag
#    - makezero
#    - inamedparam
#    - goerr113
#    - godox       #- searches FixMe,TODO in code
#    - forbidigo
#    - exhaustruct
#    - unparam
#------------------------------------
  fast: true
linters-settings:
  gosec:
    excludes:
      - G101
      - G601
      - G602
  staticcheck:
    checks: [ "all", "-SA1019"]
  stylecheck:
    checks: [ "all", "-ST1003", "-ST1023" ]
  unparam:
    check-exported: true
  misspell:
    ignore-words:
      - untill
  revive:
  # see https://github.com/mgechev/revive#available-rules for details.
    ignore-generated-header: true
    severity: warning
    rules:
      - name: indent-error-flow
        severity: warning
      - name: add-constant
        severity: warning
        arguments:
          - maxLitCount: "3"
            allowStrs: '""'
            allowInts: "0,1,2"
            allowFloats: "0.0,0.,1.0,1.,2.0,2."
  gomnd:
    ignored-files:
      - "pkg/vit/consts.go"
    ignored-numbers:
      - "0"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "10"
      - "32"
      - "42"
      - "43"
      - "100"
  testifylint:
    disable-all: true
    enable:
      - bool-compare
      - compares
      - empty
      - error-is-as
      - error-nil
      - expected-actual
      - len
      - require-error
      - suite-dont-use-pkg
      - suite-extra-assert-call
      - suite-thelper
  gocritic:
    disabled-checks:
      - appendAssign
      - dupArg
      - ifElseChain
      - singleCaseSwitch
      - exitAfterDefer
      - commentFormatting
  nilnil:
    checked-types:
      - func
  goconst:
    ignore-tests: true
issues:
  exclude:
   - underscore
   - underscores
  exclude-rules:
   - path: _test.go
     linters:
       - revive
       - gosec
       - errcheck
       - forcetypeassert
