// Code generated by "stringer -type=ProcKind -output=proc-kind_string.go"; DO NOT EDIT.

package appparts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProcKind_Command-0]
	_ = x[ProcKind_Query-1]
	_ = x[ProcKind_Projector-2]
	_ = x[ProcKind_Count-3]
}

const _ProcKind_name = "ProcKind_CommandProcKind_QueryProcKind_ProjectorProcKind_Count"

var _ProcKind_index = [...]uint8{0, 16, 30, 48, 62}

func (i ProcKind) String() string {
	if i >= ProcKind(len(_ProcKind_index)-1) {
		return "ProcKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProcKind_name[_ProcKind_index[i]:_ProcKind_index[i+1]]
}
