// Code generated by "stringer -type=ProcessorKind"; DO NOT EDIT.

package appparts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProcessorKind_Command-0]
	_ = x[ProcessorKind_Query-1]
	_ = x[ProcessorKind_Actualizer-2]
	_ = x[ProcessorKind_Scheduler-3]
	_ = x[ProcessorKind_Count-4]
}

const _ProcessorKind_name = "ProcessorKind_CommandProcessorKind_QueryProcessorKind_ActualizerProcessorKind_SchedulerProcessorKind_Count"

var _ProcessorKind_index = [...]uint8{0, 21, 40, 64, 87, 106}

func (i ProcessorKind) String() string {
	if i >= ProcessorKind(len(_ProcessorKind_index)-1) {
		return "ProcessorKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProcessorKind_name[_ProcessorKind_index[i]:_ProcessorKind_index[i+1]]
}
