-- package consists of schema and resources
-- schema consists of few schema files
SCHEMA Air;

IMPORT SCHEMA "github.com/untillpro/untill";
IMPORT SCHEMA "github.com/untillpro/airsbp" AS Air;

-- Declare comment to assign it later to definition(s)
COMMENT BackofficeComment "Backoffice Comment";

-- Declare tag to assign it later to definition(s)
TAG BackofficeTag;

-- Declares ROLE
ROLE UntillPaymentsUser;

-- TABLE ... OF - declares the inheritance from type or table. PROJECTORS from the base table are not inherted.
TABLE AirTablePlan INHERITS CDOC (
    FState int,
    Name text NOT NULL,
    VerifiableField text NOT NULL VERIFIABLE, -- Verifiable field
    Int1 int DEFAULT 1 CHECK(Int1 >= 1 AND Int2 < 10000),  -- Expressions evaluating to TRUE or UNKNOWN succeed.
    Text1 text DEFAULT "a",
    Int2 int DEFAULT NEXTVAL('sequence'),
    BillID int64 REFERENCES air.bill,
    CheckedField text CHECK "^[0-9]{8}$", -- Field validated by regexp
    CHECK (ValidateRow(this)), -- Unnamed CHECK table constraint. Expressions evaluating to TRUE or UNKNOWN succeed.
    CONSTRAINT StateChecker CHECK (ValidateFState(FState)), -- Named CHECK table constraint
    UNIQUE (FState, Name) -- unnamed UNIQUE table constraint
) WITH Comment=BackofficeComment, Tags=[BackofficeTag]; -- Optional comment and tags


-- Singletones are always CDOC. Error is thrown on attempt to declare it as WDOC or ODOC
TABLE SubscriptionProfile INHERITS SINGLETONE (
    CustomerID text,
    CustomerKind int,
    CompanyName text
);

-- Package-level extensions
EXTENSION ENGINE WASM (

    -- Function which takes sys.TableRow (unnamed param), returns boolean and implemented in WASM module in this package
    FUNCTION ValidateRow(TableRow) RETURNS boolean;

    -- Function which takes named parameter, returns boolean, and implemented in WASM module in this package
    FUNCTION ValidateFState(State int) RETURNS boolean;

);

WORKSPACE MyWorkspace (
    DESCRIPTOR OF TypeWithName ( -- Workspace descriptor is always SINGLETONE. Error is thrown on attempt to declare it as WDOC or ODOC
        Country text CHECK "^[A-Za-z]{2}$",
        Description text
    );

    -- Declare comments, tags and roles which only available in this workspace
    COMMENT PosComment "Pos Comment";
    TAG PosTag;
    ROLE LocationManager;

    -- Declare rates
    RATE BackofficeFuncRate1 1000 PER HOUR;
    RATE BackofficeFuncRate2 100 PER MINUTE PER IP;

    -- It is only allowed create table if it is defined in this workspace, or added with USE statement
	USE TABLE AirTablePlan;
	USE TABLE SomeSchema.SomeTable;
	USE TABLE Untill.*; 

    TYPE TypeWithName (
        Name text
    );
    TYPE TypeWithKind (
        Kind int
    );

    TABLE WsTable INHERITS CDOC OF Air.TypeWithName, TypeWithKind ( -- Multiple types
        PsName text,
        TABLE Child (
            Number int				
        )
    );	

    -- Workspace-level extensions 
    EXTENSION ENGINE BUILTIN (

        -- Projectors can only be declared in workspaces. Function can only take sys.Event as argument and return void.
        PROJECTOR SomeProjector1 ON COMMAND Air.Orders2;
        PROJECTOR SomeProjector2 ON COMMAND ARGUMENT TypeWithName;
        PROJECTOR SomeProjector3 ON INSERT Air.AirTablePlan;
        PROJECTOR SomeProjector4 ON INSERT OR UPDATE IN (Air.AirTablePlan, WsTable);
        PROJECTOR SomeProjector5 ON UPDATE Air.AirTablePlan;
        PROJECTOR SomeProjector6 ON UPDATE OR INSERT Air.AirTablePlan;
        PROJECTOR SomeProjector7 ON ACTIVATE Air.AirTablePlan; -- Triggered when Article is activated
        PROJECTOR SomeProjector8 ON ACTIVATE OR DEACTIVATE Air.AirTablePlan; -- Triggered when Article is activated or deactivated
        PROJECTOR ApplyUPProfile ON COMMAND IN (Air.Orders2, Air.Orders3);

        -- Commands can only be declared in workspaces
        COMMAND Orders2(Untill.Orders);
        
        -- Command with declared Comment, Tags and Rate
        COMMAND Orders3(Order Untill.Orders, Untill.PBill) WITH 
            Comment=Air.PosComment, 
            Tags=[BackofficeTag, Air.PosTag],
            Rate=BackofficeFuncRate1; 

        -- Qieries can only be declared in workspaces
        QUERY Query1 RETURNS text;
        QUERY _Query1() RETURNS text WITH Comment=Air.PosComment, Tags=[BackofficeTag, Air.PosTag];
        QUERY Query2(Order Untill.Orders, Untill.PBill) RETURNS text;
    );

    -- ACLs
    GRANT ALL ON ALL TABLES WITH TAG untill.Backoffice TO LocationManager;
    GRANT INSERT,UPDATE ON ALL TABLES WITH TAG sys.ODoc TO LocationUser;
    GRANT SELECT ON TABLE Untill.Orders TO LocationUser;
    GRANT EXECUTE ON COMMAND Orders TO LocationUser;
    GRANT EXECUTE ON QUERY TransactionHistory TO LocationUser;
    GRANT EXECUTE ON ALL QUERIES WITH TAG PosTag TO LocationUser;


    -- VIEW generated by PROJECTOR. 
    -- Primary Key must be declared in View.
    VIEW XZReports(
        Year int32,
        Month int32, 
        Day int32, 
        Kind int32, 
        Number int32, 
        XZReportWDocID id,
        PRIMARY KEY ((Year), Month, Day, Kind, Number)
    ) AS RESULT OF Air.UpdateXZReportsView;
);

ABSTRACT WORKSPACE AWorkspace (
    -- Abstract workspaces cannot be created
);

WORKSPACE MyWorkspace1 OF AWorkspace (
    -- Inherits everything declared in AWorkspace
    POOL OF WORKSPACE MyPool ()
);
