/*
 * Copyright (c) 2021-present Sigma-Soft, Ltd.
 * @author: Nikolay Nikitin
 * Copyright (c) 2021-present unTill Pro, Ltd.
 * @author: Maxim Geraskin
 */

package istructs

import (
	"math"

	"github.com/voedger/voedger/pkg/appdef"
)

// *********************************************************************************************************
//
//				QName- & Names- related constants
//

var (
	// QNameForError is a marker of error in log
	QNameForError = appdef.NewQName(appdef.SysPackage, "Error")

	// QNameForCorruptedData is marker of corrupted event records in log
	QNameForCorruptedData = appdef.NewQName(appdef.SysPackage, "Corrupted")

	// QNameCommand is used in core-irates
	QNameCommand = appdef.NewQName(appdef.SysPackage, "Command")

	// QNameQuery is used in core-irates
	QNameQuery = appdef.NewQName(appdef.SysPackage, "Query")

	QNameCommandCUD = appdef.NewQName(appdef.SysPackage, "CUD")

	// QNameRaw denotes that Function argument comes as a JSON object
	QNameRaw = appdef.NewQName(appdef.SysPackage, "Raw")

	QNameCDoc    = appdef.NewQName(appdef.SysPackage, "CDoc")
	QNameWDoc    = appdef.NewQName(appdef.SysPackage, "WDoc")
	QNameODoc    = appdef.NewQName(appdef.SysPackage, "ODoc")
	QNameCRecord = appdef.NewQName(appdef.SysPackage, "CRecord")
	QNameWRecord = appdef.NewQName(appdef.SysPackage, "WRecord")
	QNameORecord = appdef.NewQName(appdef.SysPackage, "ORecord")

	// sequences QNames has hardcoded QNameIDs: [QNameIDWLogOffsetSequence] etc
	QNameWLogOffsetSequence = appdef.NewQName(appdef.SysPackage, "WLogOffsetSequence")
	QNameRecordIDSequence   = appdef.NewQName(appdef.SysPackage, "RecordIDSequence")
)

// *********************************************************************************************************
//
//				Record-related constants
//

// Null entities do not exist, Null-representations are returned

const NullRecordID = RecordID(0)
const NullOffset = Offset(0)
const FirstOffset = Offset(1)

// MinRawRecordID and MaxRawRecordID: range bounds for "raw" RecordIDs which are generated by client and must be re-generated
const MinRawRecordID = RecordID(1)
const MaxRawRecordID = RecordID(0xffff)

// *********************************************************************************************************
//
//				Events-related constants
//

// It is 0x7FFF_FFFF_FFFF_FFFF for x64 architecture, ref. https://play.golang.org/p/HBoCflcoERV
// Used by IEvents.Read* methods
const ReadToTheEnd = int(^uint(0) >> 1)

// *********************************************************************************************************
//
//				Workspace-related constants
//

// RecordIDs range layout
//
// ────────────────────┼──────────────────────────┐
// 0                   | NullRecordID             |
// ────────────────────┼──────────────────────────┤
// 1                   | MinRawRecordID           |
// ...                 |                          |
// 65535               | MaxRawRecordID           |
// ────────────────────┼──────────────────────────┤
// 65536               | MinReservedRecordID      |
//                     | FirstSingletonID         |
// ...                 |                          |
// 66047               | MaxSingletonID           |
// 66048               | NonExistingRecordID      |
// ...                 |                          |
// 200000              | MaxReservedRecordID      |
// ────────────────────┼──────────────────────────┤
// 200001              | FirstUserRecordID        |

const NullWSID = WSID(0)

// WSID = ClusterID << WSIDClusterLShift + NextWSID()
const WSIDClusterLShift = 64 - 16 - 1

const MaxBaseWSID = 1<<WSIDClusterLShift - 1

const MinReservedRecordID = MaxRawRecordID + 1
const MaxReservedRecordID = RecordID(200000)
const MaxAllowedWSID = math.MaxUint64 >> 1

// Singleton - CDoc which has at most one record
const FirstSingletonID = MinReservedRecordID
const MaxSingletonID = FirstSingletonID + 0x1ff

// Used to test behaviour on providing the unexisting record ID
const NonExistingRecordID = MaxSingletonID + 1

// This is the first value which must be returned by the IDGenerator (in the Command Processor) for the given workspace
const FirstUserRecordID = MaxReservedRecordID + 1

// Pseudo Workspaces

const FirstPseudoBaseWSID = NullWSID
const MaxPseudoBaseWSID = WSID(0xffff)

// Application Workspaces

const FirstBaseAppWSID = MaxPseudoBaseWSID + 1
const MaxNumAppWorkspaces = 0x8000 // 32768

// Reserved WSIDs

const FirstReservedWSID = FirstBaseAppWSID + MaxNumAppWorkspaces // 0x18000, 98304
const NumReservedWSID = 0x7fff                                   // 32767

const (
	GuestWSID               = FirstReservedWSID + iota // 0x18000, 98304
	LastCurrentReservedWSID                            // Can be changed in the future
)

// User Workspaces
const FirstBaseUserWSID = FirstBaseAppWSID + 0xffff

// *********************************************************************************************************
//
//				Cluster-related constants
//

const (
	NullClusterID = ClusterID(iota)
	MainClusterID_useWithCare
)
const MaxClusterID = ClusterID(0xffff)

// Cluster application IDs

const (
	ClusterAppID_null = ClusterAppID(0) + iota
	ClusterAppID_sys_registry
	ClusterAppID_untill_airs_bp
	ClusterAppID_test1_app1
	ClusterAppID_test1_app2
	ClusterAppID_test2_app1
	ClusterAppID_test2_app2
	ClusterAppID_sys_blobber // Deprecated: not used as app anymore
	ClusterAppID_sys_router  // Deprecated: not used as app anymore
	ClusterAppID_untill_resellerportal
	ClusterAppID_sys_cluster
	ClusterAppID_untill_fiscalcloud
	ClusterAppID_FakeLast
)

const NullClusterAppID = ClusterAppID_null
const FirstGeneratedAppID = ClusterAppID(0x100)

// Cluster application qnames
const SysOwner = "sys"

var AppQName_null = appdef.NullAppQName
var AppQName_sys_registry = appdef.NewAppQName(SysOwner, "registry")
var AppQName_untill_airs_bp = appdef.NewAppQName("untill", "airs-bp")
var AppQName_test1_app1 = appdef.NewAppQName("test1", "app1")
var AppQName_test1_app2 = appdef.NewAppQName("test1", "app2")
var AppQName_test2_app1 = appdef.NewAppQName("test2", "app1")
var AppQName_test2_app2 = appdef.NewAppQName("test2", "app2")
var AppQName_sys_blobber = appdef.NewAppQName(SysOwner, "blobber") // Deprecated: not used as app anymore
var AppQName_sys_router = appdef.NewAppQName(SysOwner, "router")   // Deprecated: not used as app anymore. Used before for ACME certificates
var AppQName_untill_resellerportal = appdef.NewAppQName("untill", "resellerportal")
var AppQName_sys_cluster = appdef.NewAppQName(SysOwner, "cluster")
var AppQName_untill_fiscalcloud = appdef.NewAppQName("untill", "fiscalcloud")
var AppQName_sys_vvm = appdef.NewAppQName(SysOwner, "vvm") // used for storage only

// Cluster applications

var ClusterApps = map[appdef.AppQName]ClusterAppID{
	AppQName_null:                  ClusterAppID_null,
	AppQName_sys_registry:          ClusterAppID_sys_registry,
	AppQName_test1_app1:            ClusterAppID_test1_app1,
	AppQName_test1_app2:            ClusterAppID_test1_app2,
	AppQName_test2_app1:            ClusterAppID_test2_app1,
	AppQName_test2_app2:            ClusterAppID_test2_app2,
	AppQName_untill_airs_bp:        ClusterAppID_untill_airs_bp,
	AppQName_sys_blobber:           ClusterAppID_sys_blobber,
	AppQName_sys_router:            ClusterAppID_sys_router,
	AppQName_untill_resellerportal: ClusterAppID_untill_resellerportal,
	AppQName_sys_cluster:           ClusterAppID_sys_cluster,
	AppQName_untill_fiscalcloud:    ClusterAppID_untill_fiscalcloud,
}

const (
	RateLimitKind_byApp RateLimitKind = iota
	RateLimitKind_byWorkspace
	RateLimitKind_byID

	RateLimitKind_FakeLast
)

const DefaultNumAppWorkspaces = NumAppWorkspaces(10)

const SysGuestLogin = appdef.SysPackage + ".Guest"

func CurrentClusterID() ClusterID {
	return MainClusterID_useWithCare
}

// IDs for wellknown QNames
const (
	NullQNameID QNameID = 0 + iota
	QNameIDForError
	QNameIDCommandCUD
	QNameIDForCorruptedData
	QNameIDWLogOffsetSequence
	QNameIDRecordIDSequence

	QNameIDSysLast QNameID = 0xFF
)
