// Code generated by "stringer -type=State -output=stringer_state.go"; DO NOT EDIT.

package invite

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[State_Null-0]
	_ = x[State_ToBeInvited-1]
	_ = x[State_Invited-2]
	_ = x[State_ToBeJoined-3]
	_ = x[State_Joined-4]
	_ = x[State_ToUpdateRoles-5]
	_ = x[State_ToBeCancelled-6]
	_ = x[State_Cancelled-7]
	_ = x[State_ToBeLeft-8]
	_ = x[State_Left-9]
	_ = x[State_FakeLast-10]
}

const _State_name = "State_NullState_ToBeInvitedState_InvitedState_ToBeJoinedState_JoinedState_ToUpdateRolesState_ToBeCancelledState_CancelledState_ToBeLeftState_LeftState_FakeLast"

var _State_index = [...]uint8{0, 10, 27, 40, 56, 68, 87, 106, 121, 135, 145, 159}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
