{
 "title": "App Processors",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "App", "query": { "query": "label_values(app)" } },
   { "name": "aggregation_interval", "label": "Aggregation interval", "query": "1h,1m,5m,30m,1d" },
   { "name": "filtered_app", "label": "filtered_app", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center; font-size:200%\">\r\nCommand processors\r\n<div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center; font-size:200%\">\r\nQuery processors\r\n<div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center; font-size:200%\">\r\nActualizers\r\n<div>"
   }
  },
  {
   "title": "Commands, per $aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " increase(voedger_cp_commands_total{app=~\"$app\"}[$aggregation_interval]) ",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Queries, per $aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(voedger_qp_queries_total{app=~\"$app\"}[$aggregation_interval])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Projectors in error state (now)",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "expr": "voedger_projectors_in_error{app=~\"$app\"}",
     "legendFormat": "$app"
    }
   ]
  },
  {
   "title": "Latency, avg per $aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(voedger_cp_commands_seconds{app=~\"$app\"}[$aggregation_interval])/increase(voedger_cp_commands_total{app=~\"$app\"}[$aggregation_interval])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Latency, avg per $aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(voedger_qp_queries_seconds{app=~\"$app\"}[$aggregation_interval])/increase(voedger_qp_queries_total{app=~\"$app\"}[$aggregation_interval]) > 0 or on() increase(voedger_qp_queries_total{app=~\"$app\"}[$aggregation_interval])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Projectors in error state (history)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum by (app) (voedger_projectors_in_error{app=~\"$app\"})",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Errors, per $aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (app) (increase(voedger_cp_errors_total{app=~\"$app\"}[$aggregation_interval]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Errors, per $aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(voedger_qp_errors_total{app=~\"$app\"}[$aggregation_interval])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Overall CP",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (app) (increase(voedger_cp_commands_total{app=~\"$app\"}[$__range]))",
     "legendFormat": "Total commands"
    },
    {
     "expr": "avg by (app) (increase(voedger_cp_commands_seconds{app=~\"$app\"}[$__range]))/avg by (app) (increase(voedger_cp_commands_total{app=~\"$app\"}[$__range]))>0 OR on() increase(voedger_cp_commands_total{app=~\"$app\"}[$__range])",
     "legendFormat": "Avg Latency"
    },
    {
     "expr": "sum by (app) (increase(voedger_cp_errors_total{app=~\"$app\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Overall QP",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (app) (increase(voedger_qp_queries_total{app=~\"$app\"}[$__range]))",
     "legendFormat": "Value"
    },
    {
     "expr": "avg by (app) (increase(voedger_qp_queries_seconds{app=~\"$app\"}[$__range]))/avg by (app) (increase(voedger_qp_queries_total{app=~\"$app\"}[$__range]))>0 OR on() increase(voedger_qp_queries_total{app=~\"$app\"}[$__range])"
    },
    {
     "expr": "sum by (app) (increase(voedger_qp_errors_total{app=~\"$app\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Latency stacks: $filtered_app",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "filtered_app",
   "collapsed": true,
   "panels": [
    {
     "title": "CP latency stack, avg per $aggregation_interval",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(increase(voedger_cp_exec_seconds{app=~\"$filtered_app\"}[$aggregation_interval]))*1000/voedger_cp_commands_total{app=~\"$filtered_app\"}/sum(increase(voedger_cp_commands_total{app=~\"$filtered_app\"}[$aggregation_interval]))",
       "legendFormat": "Exec"
      },
      {
       "expr": "sum(increase(voedger_cp_projectors_seconds{app=~\"$filtered_app\"}[$aggregation_interval]))*1000/sum(increase(voedger_cp_commands_total{app=~\"$filtered_app\"}[$aggregation_interval]))",
       "legendFormat": "Projectors"
      },
      {
       "expr": "((sum(increase(voedger_cp_commands_seconds{app=~\"$filtered_app\"}[$aggregation_interval])) - sum(increase(voedger_cp_projectors_seconds{app=~\"$filtered_app\"}[$aggregation_interval])) - sum(increase(voedger_cp_exec_seconds{app=~\"$filtered_app\"}[$aggregation_interval]))))*1000/sum(increase(voedger_cp_commands_total{app=~\"$filtered_app\"}[$aggregation_interval]))",
       "legendFormat": "Rest"
      }
     ]
    },
    {
     "title": "QP latency stack, avg per $aggregation_interval",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(increase(voedger_qp_exec_seconds{app=~\"$filtered_app\"}[$aggregation_interval]) or vector(0))/sum(increase(voedger_qp_queries_total{app=~\"$filtered_app\"}[$aggregation_interval])  > 0 or on() increase(voedger_qp_queries_total{app=~\"$filtered_app\"}[$aggregation_interval]))",
       "legendFormat": "Exec"
      },
      {
       "expr": "(sum(increase(voedger_qp_exec_fields_seconds{app=~\"$filtered_app\"}[$aggregation_interval]) or vector(0)) + sum(increase(voedger_qp_exec_enrich_seconds{app=~\"$filtered_app\"}[$aggregation_interval]) or vector(0)) + sum(increase(voedger_qp_exec_filter_seconds{app=~\"$filtered_app\"}[$aggregation_interval]) or vector(0)) + sum(increase(voedger_qp_exec_order_seconds{app=~\"$filtered_app\"}[$aggregation_interval]) or vector(0)) + sum(increase(voedger_qp_exec_count_seconds{app=~\"$filtered_app\"}[$aggregation_interval]) or vector(0)) + sum(increase(voedger_qp_exec_send_seconds{app=~\"$filtered_app\"}[$aggregation_interval]) or vector(0)))/sum(increase(voedger_qp_queries_total{app=~\"$filtered_app\"}[$aggregation_interval]) > 0 or on() increase(voedger_qp_queries_total{app=~\"$filtered_app\"}[$aggregation_interval]))",
       "legendFormat": "Rows processing"
      }
     ]
    },
    {
     "title": "QP rows processing latency stack, avg per $aggregation_interval",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(increase(voedger_qp_exec_fields_seconds{app=~\"$filtered_app\"}[$aggregation_interval]) or vector(0))*1000/sum(increase(voedger_qp_queries_total{app=~\"$filtered_app\"}[$aggregation_interval])  > 0 or on() increase(voedger_qp_queries_total{app=~\"$filtered_app\"}[$aggregation_interval]))",
       "legendFormat": "Exec: Fields"
      },
      {
       "expr": "sum(increase(voedger_qp_exec_enrich_seconds{app=~\"$filtered_app\"}[$aggregation_interval]) or vector(0))*1000/sum(increase(voedger_qp_queries_total{app=~\"$filtered_app\"}[$aggregation_interval])  > 0 or on() increase(voedger_qp_queries_total{app=~\"$filtered_app\"}[$aggregation_interval]))",
       "legendFormat": "Exec: Enrich"
      },
      {
       "expr": "sum(increase(voedger_qp_exec_filter_seconds{app=~\"$filtered_app\"}[$aggregation_interval]) or vector(0))*1000/sum(increase(voedger_qp_queries_total{app=~\"$filtered_app\"}[$aggregation_interval])  > 0 or on() increase(voedger_qp_queries_total{app=~\"$filtered_app\"}[$aggregation_interval]))",
       "legendFormat": "Exec: Filter"
      },
      {
       "expr": "sum(increase(voedger_qp_exec_order_seconds{app=~\"$filtered_app\"}[$aggregation_interval]) or vector(0))*1000/sum(increase(voedger_qp_queries_total{app=~\"$filtered_app\"}[$aggregation_interval])  > 0 or on() increase(voedger_qp_queries_total{app=~\"$filtered_app\"}[$aggregation_interval]))",
       "legendFormat": "Exec: Order"
      },
      {
       "expr": "sum(increase(voedger_qp_exec_count_seconds{app=~\"$filtered_app\"}[$aggregation_interval]) or vector(0))*1000/sum(increase(voedger_qp_queries_total{app=~\"$filtered_app\"}[$aggregation_interval])  > 0 or on() increase(voedger_qp_queries_total{app=~\"$filtered_app\"}[$aggregation_interval]))",
       "legendFormat": "Exec: Count"
      },
      {
       "expr": "sum(increase(voedger_qp_exec_send_seconds{app=~\"$filtered_app\"}[$aggregation_interval]) or vector(0))*1000/sum(increase(voedger_qp_queries_total{app=~\"$filtered_app\"}[$aggregation_interval])  > 0 or on() increase(voedger_qp_queries_total{app=~\"$filtered_app\"}[$aggregation_interval]))",
       "legendFormat": "Exec: Send"
      }
     ]
    }
   ]
  }
 ]
}