// Code generated by "stringer -type APIPath"; DO NOT EDIT.

package processors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[APIPath_null-0]
	_ = x[APIPath_Docs-1]
	_ = x[APIPath_CDocs-2]
	_ = x[APIPath_Queries-3]
	_ = x[APIPath_Views-4]
	_ = x[APIPath_Commands-5]
	_ = x[APIPaths_Schema-6]
	_ = x[APIPath_Schemas_WorkspaceRoles-7]
	_ = x[APIPath_Schemas_WorkspaceRole-8]
	_ = x[APIPath_Auth_Login-9]
	_ = x[APIPath_Auth_Refresh-10]
	_ = x[APIPath_Users-11]
}

const _APIPath_name = "APIPath_nullAPIPath_DocsAPIPath_CDocsAPIPath_QueriesAPIPath_ViewsAPIPath_CommandsAPIPaths_SchemaAPIPath_Schemas_WorkspaceRolesAPIPath_Schemas_WorkspaceRoleAPIPath_Auth_LoginAPIPath_Auth_RefreshAPIPath_Users"

var _APIPath_index = [...]uint8{0, 12, 24, 37, 52, 65, 81, 96, 126, 155, 173, 193, 206}

func (i APIPath) String() string {
	if i < 0 || i >= APIPath(len(_APIPath_index)-1) {
		return "APIPath(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _APIPath_name[_APIPath_index[i]:_APIPath_index[i+1]]
}
