{
 "title": "App processors v2-2",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "App", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center; font-size:200%\">\r\nCommand Processor\r\n<div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center; font-size:200%\">\r\nQuery Processor\r\n<div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center; font-size:200%\">\r\nProjectors\r\n<div>"
   }
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " irate(voedger_cp_commands_total{app=~\"$app\"}[5m]) ",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(voedger_qp_queries_total{app=~\"$app\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Projectors in Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "expr": "sum by (app) (voedger_projectors_in_error{app=~\"$app\"})",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(voedger_cp_commands_seconds{app=~\"$app\"}[5m])/irate(voedger_cp_commands_total{app=~\"$app\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(voedger_qp_queries_seconds{app=~\"$app\"}[5m])/irate(voedger_qp_queries_total{app=~\"$app\"}[5m]) > 0 or on() irate(voedger_qp_queries_total{app=~\"$app\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Projectors in Errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "voedger_projectors_in_error{app=~\"$app\"}",
     "legendFormat": "$app"
    }
   ]
  },
  {
   "title": "Errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (app) (increase(voedger_cp_errors_total{app=~\"$app\"}[1m]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(voedger_qp_errors_total{app=~\"$app\"}[1m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Overall CP",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (app) (increase(voedger_cp_commands_total{app=~\"$app\"}[$__range]))",
     "legendFormat": "Total commands"
    },
    {
     "expr": "avg by (app) (increase(voedger_cp_commands_seconds{app=~\"$app\"}[$__range]))/avg by (app) (increase(voedger_cp_commands_total{app=~\"$app\"}[$__range]))>0 OR on() increase(voedger_cp_commands_total{app=~\"$app\"}[$__range])",
     "legendFormat": "Avg Latency"
    },
    {
     "expr": "sum by (app) (increase(voedger_cp_errors_total{app=~\"$app\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Overall QP",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (app) (increase(voedger_qp_queries_total{app=~\"$app\"}[$__range]))",
     "legendFormat": "Value"
    },
    {
     "expr": "avg by (app) (increase(voedger_qp_queries_seconds{app=~\"$app\"}[$__range]))/avg by (app) (increase(voedger_qp_queries_total{app=~\"$app\"}[$__range]))>0 OR on() increase(voedger_qp_queries_total{app=~\"$app\"}[$__range])"
    },
    {
     "expr": "sum by (app) (increase(voedger_qp_errors_total{app=~\"$app\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Latency Stack: $app",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "app",
   "collapsed": true,
   "panels": [
    {
     "title": "CP Stack Time: $app",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(voedger_cp_exec_seconds{app=~\"$app\"}[5m]))/sum(irate(voedger_cp_commands_seconds{app=~\"$app\"}[5m]))",
       "legendFormat": "Exec"
      },
      {
       "expr": "sum(irate(voedger_cp_projectors_seconds{app=~\"$app\"}[5m]))/sum(irate(voedger_cp_commands_seconds{app=~\"$app\"}[5m]))",
       "legendFormat": "Projectors"
      },
      {
       "expr": "(sum(irate(voedger_cp_commands_seconds{app=~\"$app\"}[5m])) - sum(irate(voedger_cp_projectors_seconds{app=~\"$app\"}[5m])) - sum(irate(voedger_cp_exec_seconds{app=~\"$app\"}[5m])))/sum(irate(voedger_cp_commands_seconds{app=~\"$app\"}[5m]))",
       "legendFormat": "Rest"
      }
     ]
    },
    {
     "title": "QP Stack Time: $app",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(irate(voedger_qp_exec_seconds{app=~\"$app\"}[5m]) or vector(0))/sum(irate(voedger_qp_queries_total{app=~\"$app\"}[5m])  > 0 or on() irate(voedger_qp_queries_total{app=~\"$app\"}[5m]))",
       "legendFormat": "Exec"
      },
      {
       "expr": "(sum(irate(voedger_qp_exec_fields_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_enrich_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_filter_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_order_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_count_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_send_seconds{app=~\"$app\"}[5m]) or vector(0)))/sum(irate(voedger_qp_queries_total{app=~\"$app\"}[5m]) > 0 or on() irate(voedger_qp_queries_total{app=~\"$app\"}[5m]))",
       "legendFormat": "Rows Processing"
      }
     ]
    },
    {
     "title": "QP Rows Processing Stack Time: $app",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(voedger_qp_exec_fields_seconds{app=~\"$app\"}[5m]) or vector(0))/(sum(irate(voedger_qp_exec_fields_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_enrich_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_filter_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_order_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_count_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_send_seconds{app=~\"$app\"}[5m]) or vector(0)))",
       "legendFormat": "Exec: Fields"
      },
      {
       "expr": "sum(irate(voedger_qp_exec_enrich_seconds{app=~\"$app\"}[5m]) or vector(0))/(sum(irate(voedger_qp_exec_fields_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_enrich_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_filter_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_order_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_count_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_send_seconds{app=~\"$app\"}[5m]) or vector(0)))",
       "legendFormat": "Exec: Enrich"
      },
      {
       "expr": "sum(irate(voedger_qp_exec_filter_seconds{app=~\"$app\"}[5m]) or vector(0))/(sum(irate(voedger_qp_exec_fields_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_enrich_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_filter_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_order_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_count_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_send_seconds{app=~\"$app\"}[5m]) or vector(0)))",
       "legendFormat": "Exec: Filter"
      },
      {
       "expr": "sum(irate(voedger_qp_exec_order_seconds{app=~\"$app\"}[5m]) or vector(0))/(sum(irate(voedger_qp_exec_fields_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_enrich_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_filter_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_order_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_count_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_send_seconds{app=~\"$app\"}[5m]) or vector(0)))",
       "legendFormat": "Exec: Order"
      },
      {
       "expr": "sum(irate(voedger_qp_exec_count_seconds{app=~\"$app\"}[5m]) or vector(0))/(sum(irate(voedger_qp_exec_fields_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_enrich_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_filter_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_order_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_count_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_send_seconds{app=~\"$app\"}[5m]) or vector(0)))",
       "legendFormat": "Exec: Count"
      },
      {
       "expr": "sum(irate(voedger_qp_exec_send_seconds{app=~\"$app\"}[5m]) or vector(0))/(sum(irate(voedger_qp_exec_fields_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_enrich_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_filter_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_order_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_count_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_send_seconds{app=~\"$app\"}[5m]) or vector(0)))",
       "legendFormat": "Exec: Send"
      }
     ]
    }
   ]
  }
 ]
}