{
 "title": "App processors",
 "tags": [ "bp3" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "App", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  { "title": "Projectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Projectors in Errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "voedger_projectors_in_error{app=~\"$app\"}",
     "legendFormat": "$app"
    }
   ]
  },
  {
   "title": "Projectors in Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum by (app) (voedger_projectors_in_error{app=~\"$app\"})",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "$app Requests ",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "repeat": "app",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (app) (increase(voedger_cp_commands_total{app=~\"$app\"}[$__range])) / (sum by (app) (increase(voedger_cp_commands_total{app=~\"$app\"}[$__range])) + sum by (app) (increase(voedger_qp_queries_total{app=~\"$app\"}[$__range])))",
       "legendFormat": "Commands"
      },
      {
       "expr": "sum by (app) (increase(voedger_qp_queries_total{app=~\"$app\"}[$__range])) / (sum by (app) (increase(voedger_cp_commands_total{app=~\"$app\"}[$__range])) + sum by (app) (increase(voedger_qp_queries_total{app=~\"$app\"}[$__range])))",
       "legendFormat": "Queries"
      }
     ]
    },
    {
     "title": "Total CP invocations",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (app) (increase(voedger_cp_commands_total{app=~\"$app\"}[$__range]))",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Total QP invocations",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (app) (increase(voedger_qp_queries_total{app=~\"$app\"}[$__range]))",
       "legendFormat": "Value"
      }
     ]
    }
   ]
  },
  { "title": "Command Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CP RPS over period",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(voedger_cp_commands_total{app=~\"$app\"}[5m])",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "CP RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " irate(voedger_cp_commands_total{app=~\"$app\"}[5m]) ",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Avg CP Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (app) (increase(voedger_cp_commands_seconds{app=~\"$app\"}[$__range]))/avg by (app) (increase(voedger_cp_commands_total{app=~\"$app\"}[$__range]))>0 OR on() increase(voedger_cp_commands_total{app=~\"$app\"}[$__range])",
     "legendFormat": "Request time"
    }
   ]
  },
  {
   "title": "CP Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(voedger_cp_commands_seconds{app=~\"$app\"}[5m])/irate(voedger_cp_commands_total{app=~\"$app\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Total CP errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (app) (increase(voedger_cp_errors_total{app=~\"$app\"}[$__range]))",
     "legendFormat": "Total errors"
    }
   ]
  },
  {
   "title": "CP errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (app) (increase(voedger_cp_errors_total{app=~\"$app\"}[1m]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Query Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "QP RPS over period",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(voedger_qp_queries_total{app=~\"$app\"}[5m])",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "QP RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(voedger_qp_queries_total{app=~\"$app\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Avg QP Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (app) (increase(voedger_qp_queries_seconds{app=~\"$app\"}[$__range]))/avg by (app) (increase(voedger_qp_queries_total{app=~\"$app\"}[$__range]))>0 OR on() increase(voedger_qp_queries_total{app=~\"$app\"}[$__range])",
     "legendFormat": "Request time"
    }
   ]
  },
  {
   "title": "QP Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(voedger_qp_queries_seconds{app=~\"$app\"}[5m])/irate(voedger_qp_queries_total{app=~\"$app\"}[5m]) > 0 or on() irate(voedger_qp_queries_total{app=~\"$app\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Total QP errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (app) (increase(voedger_qp_errors_total{app=~\"$app\"}[$__range]))",
     "legendFormat": "Total errors"
    }
   ]
  },
  {
   "title": "QP errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(voedger_qp_errors_total{app=~\"$app\"}[1m])",
     "legendFormat": "Total errors"
    }
   ]
  },
  {
   "title": "Latency Stack: $app",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "repeat": "app",
   "collapsed": true,
   "panels": [
    {
     "title": "CP Stack Time: $app",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(voedger_cp_exec_seconds{app=~\"$app\"}[5m]))/sum(irate(voedger_cp_commands_seconds{app=~\"$app\"}[5m]))",
       "legendFormat": "Exec"
      },
      {
       "expr": "sum(irate(voedger_cp_projectors_seconds{app=~\"$app\"}[5m]))/sum(irate(voedger_cp_commands_seconds{app=~\"$app\"}[5m]))",
       "legendFormat": "Projectors"
      },
      {
       "expr": "(sum(irate(voedger_cp_commands_seconds{app=~\"$app\"}[5m])) - sum(irate(voedger_cp_projectors_seconds{app=~\"$app\"}[5m])) - sum(irate(voedger_cp_exec_seconds{app=~\"$app\"}[5m])))/sum(irate(voedger_cp_commands_seconds{app=~\"$app\"}[5m]))",
       "legendFormat": "Rest"
      }
     ]
    },
    {
     "title": "QP Stack Time: $app",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(irate(voedger_qp_exec_seconds{app=~\"$app\"}[5m]) or vector(0))/sum(irate(voedger_qp_queries_total{app=~\"$app\"}[5m])  > 0 or on() irate(voedger_qp_queries_total{app=~\"$app\"}[5m]))",
       "legendFormat": "Exec"
      },
      {
       "expr": "(sum(irate(voedger_qp_exec_fields_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_enrich_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_filter_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_order_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_count_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_send_seconds{app=~\"$app\"}[5m]) or vector(0)))/sum(irate(voedger_qp_queries_total{app=~\"$app\"}[5m]) > 0 or on() irate(voedger_qp_queries_total{app=~\"$app\"}[5m]))",
       "legendFormat": "Rows Processing"
      }
     ]
    },
    {
     "title": "QP Rows Processing Stack Time: $app",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(voedger_qp_exec_fields_seconds{app=~\"$app\"}[5m]) or vector(0))/(sum(irate(voedger_qp_exec_fields_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_enrich_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_filter_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_order_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_count_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_send_seconds{app=~\"$app\"}[5m]) or vector(0)))",
       "legendFormat": "Exec: Fields"
      },
      {
       "expr": "sum(irate(voedger_qp_exec_enrich_seconds{app=~\"$app\"}[5m]) or vector(0))/(sum(irate(voedger_qp_exec_fields_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_enrich_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_filter_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_order_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_count_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_send_seconds{app=~\"$app\"}[5m]) or vector(0)))",
       "legendFormat": "Exec: Enrich"
      },
      {
       "expr": "sum(irate(voedger_qp_exec_filter_seconds{app=~\"$app\"}[5m]) or vector(0))/(sum(irate(voedger_qp_exec_fields_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_enrich_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_filter_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_order_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_count_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_send_seconds{app=~\"$app\"}[5m]) or vector(0)))",
       "legendFormat": "Exec: Filter"
      },
      {
       "expr": "sum(irate(voedger_qp_exec_order_seconds{app=~\"$app\"}[5m]) or vector(0))/(sum(irate(voedger_qp_exec_fields_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_enrich_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_filter_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_order_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_count_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_send_seconds{app=~\"$app\"}[5m]) or vector(0)))",
       "legendFormat": "Exec: Order"
      },
      {
       "expr": "sum(irate(voedger_qp_exec_count_seconds{app=~\"$app\"}[5m]) or vector(0))/(sum(irate(voedger_qp_exec_fields_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_enrich_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_filter_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_order_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_count_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_send_seconds{app=~\"$app\"}[5m]) or vector(0)))",
       "legendFormat": "Exec: Count"
      },
      {
       "expr": "sum(irate(voedger_qp_exec_send_seconds{app=~\"$app\"}[5m]) or vector(0))/(sum(irate(voedger_qp_exec_fields_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_enrich_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_filter_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_order_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_count_seconds{app=~\"$app\"}[5m]) or vector(0)) + sum(irate(voedger_qp_exec_send_seconds{app=~\"$app\"}[5m]) or vector(0)))",
       "legendFormat": "Exec: Send"
      }
     ]
    }
   ]
  }
 ]
}