// Code generated by vpm. DO NOT EDIT.

package orm

import (
	"github.com/voedger/voedger/pkg/exttinygo"
)

// package type
type TPackage_air struct {
	Path                            string
	WS_RestaurantWS                 WS_air_RestaurantWS
	Type_CmdPBillResult             Type_air_CmdPBillResult
	Command_Pbill                   Command_air_Pbill
	WSingleton_NextNumbers          WSingleton_air_NextNumbers
	Command_Orders                  Command_air_Orders
	View_PbillDates                 View_air_PbillDates
	ODoc_ProformaPrinted            ODoc_air_ProformaPrinted
	CSingleton_RestaurantDescriptor CSingleton_air_RestaurantDescriptor
}

// package variables
var Package_air = TPackage_air{
	Path: "air",
	WS_RestaurantWS: WS_air_RestaurantWS{
		Type: Type{fQName: "air.RestaurantWS"},
	}, Type_CmdPBillResult: Type_air_CmdPBillResult{
		Type: Type{fQName: "air.CmdPBillResult"},
	}, Command_Pbill: Command_air_Pbill{
		Type: Type{fQName: "air.Pbill"},
	}, WSingleton_NextNumbers: WSingleton_air_NextNumbers{
		Type: Type{fQName: "air.NextNumbers"},
	}, Command_Orders: Command_air_Orders{
		Type: Type{fQName: "air.Orders"},
	}, View_PbillDates: View_air_PbillDates{
		Type: Type{fQName: "air.PbillDates"},
	}, ODoc_ProformaPrinted: ODoc_air_ProformaPrinted{
		Type: Type{fQName: "air.ProformaPrinted"},
	}, CSingleton_RestaurantDescriptor: CSingleton_air_RestaurantDescriptor{
		Type: Type{fQName: "air.RestaurantDescriptor"},
	},
}

type WS_air_RestaurantWS struct {
	Type
}

type Value_WS_air_RestaurantWS struct {
	tv exttinygo.TValue
}

type Intent_WS_air_RestaurantWS struct {
	intent exttinygo.TIntent
}

func (r WS_air_RestaurantWS) PkgPath() string {
	return Package_air.Path
}

func (r WS_air_RestaurantWS) Entity() string {
	return "RestaurantWS"
}

func (r WS_air_RestaurantWS) Descriptor() string {
	return "RestaurantDescriptor"
}

type Type_air_CmdPBillResult struct {
	Type
}

type Value_Type_air_CmdPBillResult struct {
	tv exttinygo.TValue
}

type Intent_Type_air_CmdPBillResult struct {
	intent exttinygo.TIntent
}

func (v Value_Type_air_CmdPBillResult) Get_sys_Container() string {
	return v.tv.AsString("sys_Container")
}

func (v Value_Type_air_CmdPBillResult) Get_Number() int32 {
	return v.tv.AsInt32("Number")
}

func (r Type_air_CmdPBillResult) PkgPath() string {
	return Package_air.Path
}

func (r Type_air_CmdPBillResult) Entity() string {
	return "CmdPBillResult"
}

type Command_air_Pbill struct {
	Type
}

func (r Command_air_Pbill) PkgPath() string {
	return Package_air.Path
}

func (r Command_air_Pbill) Entity() string {
	return "Pbill"
}

func (c Command_air_Pbill) ArgumentObject() Value_ODoc_untill_pbill {
	kb := exttinygo.KeyBuilder(exttinygo.StorageCommandContext, exttinygo.NullEntity)
	return Value_ODoc_untill_pbill{tv: exttinygo.MustGetValue(kb).AsValue(FieldNameEventArgumentObject)}
}

func (r Command_air_Pbill) ArgumentPkgPath() string {
	return Package_untill.ODoc_pbill.PkgPath()

}

func (r Command_air_Pbill) ArgumentEntity() string {
	return Package_untill.ODoc_pbill.Entity()

}

func (r Command_air_Pbill) WorkspaceDescriptor() string {
	return Package_air.WS_RestaurantWS.Descriptor()
}

func (c Command_air_Pbill) Result(sys_container string, number int32) {
	__result := exttinygo.NewValue(exttinygo.KeyBuilder(exttinygo.StorageResult, exttinygo.NullEntity))
	__result.PutString("sys_Container", sys_container)
	__result.PutInt32("Number", number)
}

type Projector_air_FillPbillDates struct {
	Type
	_event exttinygo.TValue
}

func (p Projector_air_FillPbillDates) Event() Event {
	return Event{
		WLogOffset: p.event().AsInt64("WLogOffset"),
	}
}

func (p Projector_air_FillPbillDates) event() exttinygo.TValue {
	if p._event == 0 {
		p._event = eventFunc()
	}
	return p._event
}

func (r Projector_air_FillPbillDates) WorkspaceDescriptor() string {
	return Package_air.WS_RestaurantWS.Descriptor()
}

func (pkg TPackage_air) Projector_FillPbillDates() Projector_air_FillPbillDates {
	return Projector_air_FillPbillDates{}
}

func (r Projector_air_FillPbillDates) PkgPath() string {
	return Package_air.Path
}

func (r Projector_air_FillPbillDates) Entity() string {
	return "FillPbillDates"
}

type Cmd_air_Pbill struct {
	qname string
	event exttinygo.TValue
}

func (c Cmd_air_Pbill) Arg() (Value_ODoc_untill_pbill, bool) {
	qname := c.event.AsQName("QName")
	if qname.FullPkgName != Package_air.Command_Pbill.PkgPath() || qname.Entity != Package_air.Command_Pbill.Entity() {
		return Value_ODoc_untill_pbill{}, false
	}

	return Value_ODoc_untill_pbill{tv: c.event.AsValue("ArgumentObject")}, true
}

func (c Cmd_air_Pbill) Event() Event {
	return Event{
		WLogOffset: c.event.AsInt64("WLogOffset"),
	}
}

func (p *Projector_air_FillPbillDates) Cmd_Pbill() Cmd_air_Pbill {
	return Cmd_air_Pbill{
		qname: p.PkgPath() + "." + "Pbill",
		event: p.event(),
	}
}

type WSingleton_air_NextNumbers struct {
	Type
}

type Value_WSingleton_air_NextNumbers struct {
	tv exttinygo.TValue
	kb exttinygo.TKeyBuilder
}

type Intent_WSingleton_air_NextNumbers struct {
	intent exttinygo.TIntent
}

func (v Value_WSingleton_air_NextNumbers) Get_NextPBillNumber() int32 {
	return v.tv.AsInt32("NextPBillNumber")
}

func (i Intent_WSingleton_air_NextNumbers) Set_NextPBillNumber(value int32) Intent_WSingleton_air_NextNumbers {
	i.intent.PutInt32("NextPBillNumber", value)
	return i
}

func (r WSingleton_air_NextNumbers) PkgPath() string {
	return Package_air.Path
}

func (r WSingleton_air_NextNumbers) Entity() string {
	return "NextNumbers"
}

func (v WSingleton_air_NextNumbers) Insert() Intent_WSingleton_air_NextNumbers {
	kb := exttinygo.KeyBuilder(exttinygo.StorageRecord, v.fQName)
	kb.PutBool(FieldName_IsSingleton, true)
	return Intent_WSingleton_air_NextNumbers{intent: exttinygo.NewValue(kb)}
}

func (v WSingleton_air_NextNumbers) Update() Intent_WSingleton_air_NextNumbers {
	existingValue := v.MustGet()
	kb := exttinygo.KeyBuilder(exttinygo.StorageRecord, v.fQName)
	kb.PutBool(FieldName_IsSingleton, true)
	return Intent_WSingleton_air_NextNumbers{intent: exttinygo.UpdateValue(kb, existingValue.tv)}
}

func (v WSingleton_air_NextNumbers) Get() (Value_WSingleton_air_NextNumbers, bool) {
	kb := exttinygo.KeyBuilder(exttinygo.StorageRecord, v.fQName)
	kb.PutBool(FieldName_IsSingleton, true)
	tv, exists := exttinygo.QueryValue(kb)
	if !exists {
		return Value_WSingleton_air_NextNumbers{kb: kb}, false
	}
	return Value_WSingleton_air_NextNumbers{tv: tv, kb: kb}, true
}

func (v WSingleton_air_NextNumbers) MustGet() Value_WSingleton_air_NextNumbers {
	kb := exttinygo.KeyBuilder(exttinygo.StorageRecord, v.fQName)
	kb.PutBool(FieldName_IsSingleton, true)
	tv := exttinygo.MustGetValue(kb)
	return Value_WSingleton_air_NextNumbers{tv: tv, kb: kb}
}

func (v Value_WSingleton_air_NextNumbers) Insert() Intent_WSingleton_air_NextNumbers {
	return Intent_WSingleton_air_NextNumbers{intent: exttinygo.NewValue(v.kb)}
}

func (v Value_WSingleton_air_NextNumbers) Update() Intent_WSingleton_air_NextNumbers {
	return Intent_WSingleton_air_NextNumbers{intent: exttinygo.UpdateValue(v.kb, v.tv)}
}

type Command_air_Orders struct {
	Type
}

func (r Command_air_Orders) PkgPath() string {
	return Package_air.Path
}

func (r Command_air_Orders) Entity() string {
	return "Orders"
}

func (c Command_air_Orders) ArgumentObject() Value_ODoc_untill_orders {
	kb := exttinygo.KeyBuilder(exttinygo.StorageCommandContext, exttinygo.NullEntity)
	return Value_ODoc_untill_orders{tv: exttinygo.MustGetValue(kb).AsValue(FieldNameEventArgumentObject)}
}

func (r Command_air_Orders) ArgumentPkgPath() string {
	return Package_untill.ODoc_orders.PkgPath()

}

func (r Command_air_Orders) ArgumentEntity() string {
	return Package_untill.ODoc_orders.Entity()

}

func (r Command_air_Orders) WorkspaceDescriptor() string {
	return Package_air.WS_RestaurantWS.Descriptor()
}

type View_air_PbillDates struct {
	Type
}

type Value_View_air_PbillDates struct {
	tv exttinygo.TValue
	kb exttinygo.TKeyBuilder
}

type Intent_View_air_PbillDates struct {
	intent exttinygo.TIntent
}

func (v Value_View_air_PbillDates) Get_FirstOffset() int64 {
	return v.tv.AsInt64("FirstOffset")
}

func (v Value_View_air_PbillDates) Get_LastOffset() int64 {
	return v.tv.AsInt64("LastOffset")
}

func (i Intent_View_air_PbillDates) Set_FirstOffset(value int64) Intent_View_air_PbillDates {
	i.intent.PutInt64("FirstOffset", value)
	return i
}

func (i Intent_View_air_PbillDates) Set_LastOffset(value int64) Intent_View_air_PbillDates {
	i.intent.PutInt64("LastOffset", value)
	return i
}

func (r View_air_PbillDates) PkgPath() string {
	return Package_air.Path
}

func (r View_air_PbillDates) Entity() string {
	return "PbillDates"
}

func (v View_air_PbillDates) Insert(year int32, dayofyear int32) Intent_View_air_PbillDates {
	kb := exttinygo.KeyBuilder(exttinygo.StorageView, v.fQName)
	kb.PutInt32("Year", year)
	kb.PutInt32("DayOfYear", dayofyear)
	return Intent_View_air_PbillDates{intent: exttinygo.NewValue(kb)}
}

func (v View_air_PbillDates) Keys() []string {
	return []string{"Year", "DayOfYear"}
}

func (v View_air_PbillDates) Update(year int32, dayofyear int32) Intent_View_air_PbillDates {
	existingValue := v.MustGet(year, dayofyear)
	kb := exttinygo.KeyBuilder(exttinygo.StorageView, v.fQName)
	kb.PutInt32("Year", year)
	kb.PutInt32("DayOfYear", dayofyear)
	return Intent_View_air_PbillDates{intent: exttinygo.UpdateValue(kb, existingValue.tv)}
}

func (v View_air_PbillDates) Get(year int32, dayofyear int32) (Value_View_air_PbillDates, bool) {
	kb := exttinygo.KeyBuilder(exttinygo.StorageView, v.fQName)
	kb.PutInt32("Year", year)
	kb.PutInt32("DayOfYear", dayofyear)
	tv, exists := exttinygo.QueryValue(kb)
	if !exists {
		return Value_View_air_PbillDates{kb: kb}, false
	}
	return Value_View_air_PbillDates{tv: tv, kb: kb}, true
}

func (v View_air_PbillDates) MustGet(year int32, dayofyear int32) Value_View_air_PbillDates {
	kb := exttinygo.KeyBuilder(exttinygo.StorageView, v.fQName)
	kb.PutInt32("Year", year)
	kb.PutInt32("DayOfYear", dayofyear)
	tv := exttinygo.MustGetValue(kb)
	return Value_View_air_PbillDates{tv: tv, kb: kb}
}

func (v Value_View_air_PbillDates) Insert() Intent_View_air_PbillDates {
	return Intent_View_air_PbillDates{intent: exttinygo.NewValue(v.kb)}
}

func (v Value_View_air_PbillDates) Update() Intent_View_air_PbillDates {
	return Intent_View_air_PbillDates{intent: exttinygo.UpdateValue(v.kb, v.tv)}
}

type ODoc_air_ProformaPrinted struct {
	Type
}

type Value_ODoc_air_ProformaPrinted struct {
	tv exttinygo.TValue
}

type Intent_ODoc_air_ProformaPrinted struct {
	intent exttinygo.TIntent
}

func (v Value_ODoc_air_ProformaPrinted) Get_Number() int32 {
	return v.tv.AsInt32("Number")
}

func (v Value_ODoc_air_ProformaPrinted) Get_UserID() ID {
	return ID(v.tv.AsInt64("UserID"))
}

func (v Value_ODoc_air_ProformaPrinted) Get_Timestamp() int64 {
	return v.tv.AsInt64("Timestamp")
}

func (v Value_ODoc_air_ProformaPrinted) Get_BillID() ID {
	return ID(v.tv.AsInt64("BillID"))
}

func (i Intent_ODoc_air_ProformaPrinted) Set_Number(value int32) Intent_ODoc_air_ProformaPrinted {
	i.intent.PutInt32("Number", value)
	return i
}

func (i Intent_ODoc_air_ProformaPrinted) Set_UserID(value ID) Intent_ODoc_air_ProformaPrinted {
	i.intent.PutInt64("UserID", int64(value))
	return i
}

func (i Intent_ODoc_air_ProformaPrinted) Set_Timestamp(value int64) Intent_ODoc_air_ProformaPrinted {
	i.intent.PutInt64("Timestamp", value)
	return i
}

func (i Intent_ODoc_air_ProformaPrinted) Set_BillID(value ID) Intent_ODoc_air_ProformaPrinted {
	i.intent.PutInt64("BillID", int64(value))
	return i
}

func (r ODoc_air_ProformaPrinted) PkgPath() string {
	return Package_air.Path
}

func (r ODoc_air_ProformaPrinted) Entity() string {
	return "ProformaPrinted"
}

func (v ODoc_air_ProformaPrinted) IAmODoc() {
	return
}

func (v ODoc_air_ProformaPrinted) QName() exttinygo.QName {
	return exttinygo.QName{FullPkgName: v.PkgPath(), Entity: v.Entity()}
}

func (v ODoc_air_ProformaPrinted) Insert(id ID) Intent_ODoc_air_ProformaPrinted {
	kb := exttinygo.KeyBuilder(exttinygo.StorageRecord, v.fQName)
	kb.PutInt64(FieldName_ID, int64(id))
	return Intent_ODoc_air_ProformaPrinted{intent: exttinygo.NewValue(kb)}
}

type CSingleton_air_RestaurantDescriptor struct {
	Type
}

type Value_CSingleton_air_RestaurantDescriptor struct {
	tv exttinygo.TValue
}

type Intent_CSingleton_air_RestaurantDescriptor struct {
	intent exttinygo.TIntent
}

func (r CSingleton_air_RestaurantDescriptor) PkgPath() string {
	return Package_air.Path
}

func (r CSingleton_air_RestaurantDescriptor) Entity() string {
	return "RestaurantDescriptor"
}
