// Code generated by vpm. DO NOT EDIT.

package orm

import "github.com/voedger/voedger/pkg/exttinygo"

type FQName = string
type ID int64
type Bytes []byte

const (
	FieldNameEventUnloggedArgumentObject = "UnloggedArgumentObject"
	FieldNameEventArgumentObject         = "ArgumentObject"
	FieldNameSysID                       = "sys.ID"
	FieldName_IsSingleton                = "IsSingleton"
	FieldName_ID                         = "ID"
)

type IFullQName interface {
	PkgPath() string
	Entity() string
}

type Type struct {
	fQName FQName
}

func (t *Type) QName() FQName {
	return t.fQName
}

type Event struct{}
type Value_CommandContext struct{ tv exttinygo.TValue }

func CommandContext() Value_CommandContext {
	kb := exttinygo.KeyBuilder(exttinygo.StorageCommandContext, exttinygo.NullEntity)
	return Value_CommandContext{tv: exttinygo.MustGetValue(kb)}
}
