// Code generated by "stringer -type=CacheProvider -output=provider_string.go"; DO NOT EDIT.

package objcache

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Hashicorp-0]
	_ = x[Theine-1]
	_ = x[Floatdrop-2]
	_ = x[Imcache-3]
}

const _CacheProvider_name = "HashicorpTheineFloatdropImcache"

var _CacheProvider_index = [...]uint8{0, 9, 15, 24, 31}

func (i CacheProvider) String() string {
	if i >= CacheProvider(len(_CacheProvider_index)-1) {
		return "CacheProvider(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CacheProvider_name[_CacheProvider_index[i]:_CacheProvider_index[i+1]]
}
