// Code generated by "stringer -type=SectionKind"; DO NOT EDIT.

package ibus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SectionKindUnspecified-0]
	_ = x[SectionKindMap-1]
	_ = x[SectionKindArray-2]
	_ = x[SectionKindObject-3]
}

const _SectionKind_name = "SectionKindUnspecifiedSectionKindMapSectionKindArraySectionKindObject"

var _SectionKind_index = [...]uint8{0, 22, 36, 52, 69}

func (i SectionKind) String() string {
	if i < 0 || i >= SectionKind(len(_SectionKind_index)-1) {
		return "SectionKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SectionKind_name[_SectionKind_index[i]:_SectionKind_index[i+1]]
}
