name: CI changes in pkg/istorage

on:
  push:
    paths:
      - 'pkg/istorage/**'
  pull_request_target:
    paths:
      - 'pkg/istorage/**'

jobs:

  determine_changes:
    runs-on: ubuntu-latest
    outputs:
      cas_changed: ${{ steps.filter.outputs.cas_changed }}
      amazon_changed: ${{ steps.filter.outputs.amazon_changed }}
      others_changed: ${{ steps.filter.outputs.others_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensure we have history for comparison

      - name: Check changed files
        id: filter
        run: |
          CAS_CHANGED=false
          AMAZON_CHANGED=false
          OTHERS_CHANGED=false

          # Ensure we have a valid previous commit
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            BEFORE_COMMIT=HEAD^
          else
            BEFORE_COMMIT=HEAD  # In case it's the first commit
          fi

          # Get changed files
          CHANGED_FILES=$(git diff --name-only $BEFORE_COMMIT HEAD)

          for FILE in $CHANGED_FILES; do
            case "$FILE" in
              pkg/istorage/cas/*)
                CAS_CHANGED=true
                ;;
              pkg/istorage/amazondb/*)
                AMAZON_CHANGED=true
                ;;
              pkg/istorage/*) 
                # If changes are in another subdirectory under pkg/istorage (e.g., bbolt, mem, provider)
                OTHERS_CHANGED=true
                ;;
            esac
          done

          echo "cas_changed=$CAS_CHANGED" >> $GITHUB_OUTPUT
          echo "amazon_changed=$AMAZON_CHANGED" >> $GITHUB_OUTPUT
          echo "others_changed=$OTHERS_CHANGED" >> $GITHUB_OUTPUT

  trigger_cas:
    needs: determine_changes
    if: (needs.determine_changes.outputs.cas_changed == 'true' && needs.determine_changes.outputs.amazon_changed == 'false') || (needs.determine_changes.outputs.others_changed == 'true')
    uses: ./.github/workflows/ci_cas.yml
    secrets:
      personaltoken: ${{ secrets.REPOREADING_TOKEN }}

  trigger_amazon:
    needs: determine_changes
    if: (needs.determine_changes.outputs.amazon_changed == 'true' && needs.determine_changes.outputs.cas_changed == 'false') || (needs.determine_changes.outputs.others_changed == 'true')
    uses: ./.github/workflows/ci_amazon.yml
    secrets:
      personaltoken: ${{ secrets.REPOREADING_TOKEN }}

  auto-merge-pr-amazon:
    needs: [trigger_amazon]
    if: ${{ github.event_name == 'pull_request_target'  }}
    uses: ./.github/workflows/merge.yml
    secrets:
      personaltoken: ${{ secrets.REPOREADING_TOKEN }}

  auto-merge-pr-cas:
    needs: [trigger_cas]
    if: ${{ github.event_name == 'pull_request_target'}}
    uses: ./.github/workflows/merge.yml
    secrets:
      personaltoken: ${{ secrets.REPOREADING_TOKEN }}

